# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79d3bffcaf603beb33de7082b6a59855f7e0087c1629fd6659cc0ea21701bf908c3f3fb622828766712e5ed467de9b6f617f6ba82b18082df4cd05b155a7c2b5

test:
  secret_key_base: bc751a5dfd0a09f3203e702544ed71dd0f08894feae4333c6fc7dbf51239f9d67839b91c3007fa513b69a2e0dc063e9e0999e58ef9f6af5349ad371a426d591a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
